[package]
name = "bitvmx-cpu-definitions"
version = "0.5.0"
edition = "2021"

[dependencies]
config = "0.15.11"
serde = "1.0.204"
thiserror = "2.0.12"
hex = "0.4.3"
blake3 = "1.6.1"
serde_json = "1.0.104"
strum = "0.27"
strum_macros = "0.27"
